spring.application.name=nepplaats
# De URL naar je lokale PostgreSQL database (vervang 'naam_van_je_database' met je echte databasenaam)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Je PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate past niks aan, maar controleert wél of je Java Entities overeenkomen met je SQL database
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:nepplaats_v2.sql
spring.sql.init.data-locations=classpath:nepplaats_db_v2.sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.continue-on-error=true


# Keycloak / OAuth2 Instellingen
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/master
client-id=nepplaats-backend
spring.security.oauth2.resourceserver.jwt.audiences=account

# Activeer HTTPS op poort 8443
server.port=8443
server.error.include-message=always

# SSL/TLS Instellingen
server.ssl.key-store=classpath:nepplaats.p12
server.ssl.key-store-password=password
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=nepplaats

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html