CREATE TABLE IF NOT EXISTS  "afbeelding" (
                              "afbeelding_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
                              "bestand_data" bytea NOT NULL,
                              "originele_naam" varchar(255) NOT NULL,
                              "bestandstype" varchar(255) NOT NULL,
                              "bestandsgrootte" bigint NOT NULL,
                              "upload_datum" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS  "categorieen" (
                               "categorie_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "categorie_beschrijving" text,
                               "categorie_naam" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS  "gebruikers" (
                              "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "beschrijving" text,
                              "email" varchar(255) UNIQUE NOT NULL,
                              "gebruikersnaam" varchar(255) UNIQUE,
                              "rol_id" bigint NOT NULL DEFAULT 2,
                              "keycloak_id" varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS  "product_posts" (
                                 "product_post_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "beschrijving" text,
                                 "categorie_id" bigint,
                                 "post_date" timestamp(6) NOT NULL,
                                 "poster_id" bigint NOT NULL,
                                 "prijs" numeric(10,2) NOT NULL,
                                 "status_id" bigint NOT NULL,
                                 "titel" varchar(255) NOT NULL,
                                 "afbeelding_id" uuid UNIQUE
);

CREATE TABLE IF NOT EXISTS  "rollen" (
                          "rol_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "rol_beschrijving" text,
                          "rol_naam" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS  "statussen" (
                             "status_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "status_beschrijving" text,
                             "status_naam" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS  "transacties" (
                               "transactie_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "koper_id" bigint NOT NULL,
                               "product_post_id" bigint UNIQUE NOT NULL,
                               "tijd" timestamp(6) NOT NULL
);

ALTER TABLE "product_posts" ADD FOREIGN KEY ("categorie_id") REFERENCES "categorieen" ("categorie_id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_posts" ADD FOREIGN KEY ("afbeelding_id") REFERENCES "afbeelding" ("afbeelding_id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_posts" ADD FOREIGN KEY ("status_id") REFERENCES "statussen" ("status_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gebruikers" ADD FOREIGN KEY ("rol_id") REFERENCES "rollen" ("rol_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_posts" ADD FOREIGN KEY ("poster_id") REFERENCES "gebruikers" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacties" ADD FOREIGN KEY ("koper_id") REFERENCES "gebruikers" ("user_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacties" ADD FOREIGN KEY ("product_post_id") REFERENCES "product_posts" ("product_post_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;
